# Generated by Django 5.0.6 on 2024-06-24 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_organizations', to='api.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Tallon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=250)),
                ('date_received', models.DateField()),
                ('tallon_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('1, 2', '1, 2'), ('1, 3', '1, 3'), ('2, 3', '2, 3'), ('1, 2, 3', '1, 2, 3')], max_length=30)),
                ('reason_received', models.CharField(max_length=255)),
                ('discipline_order', models.CharField(max_length=50)),
                ('discipline_order_date', models.DateField()),
                ('discipline_type', models.CharField(max_length=255)),
                ('consequence_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.organization')),
            ],
        ),
    ]
