# Generated by Django 5.0.6 on 2024-06-25 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_organization_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branch_organizations', to='api.branch'),
            preserve_default=False,
        ),
    ]
