# Generated by Django 5.0.6 on 2024-06-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('QONGROT_MTU', 'QONGROT_MTU'), ('TERMIZ_MTU', 'TERMIZ_MTU'), ('QARSHI_MTU', 'QARSHI_MTU'), ('BUXORO_MTU', 'BUXORO_MTU'), ('QOQON_MTU', 'QOQON_MTU'), ('TOSHKENT_MTU', 'TOSHKENT_MTU')], max_length=20),
        ),
    ]
